title: Hashgraph
email: hashgraph@bugbytes.com
description: .NET Client Library for Hedera Hashgraph
baseurl: "/Hashgraph"
url: "https://bugbytesinc.github.io"
twitter_username: bugbytesinc
github_username:  bugbytesinc
repository: bugbytesinc/hashgraph
markdown: kramdown
plugins:
  - jekyll-feed
logo: "https://raw.githubusercontent.com/bugbytesinc/Hashgraph/master/logo.png"
