#  Required secrets managed by GitHub.
#
#  PREVIEWNET_ACCOUNT_NUMBER:       The Hedera Test Account Address Number (assumes Shard = 0, Realm = 0)
#  PREVIEWNET_ACCOUNT_PUBLIC_KEY:   Public Key for the root payer account, encoded in Hex
#  PREVIEWNET_ACCOUNT_PRIVATE_KEY:  Private Key for the root payer account, encoded in Hex
#  PREVIEWNET_MIRROR_ADDRESS:       Mirror Node DNS name, for example 'PREVIEWNET.mirrornode.hedera.com'
#  PREVIEWNET_MIRROR_PORT:          Mirror Node port number
#  PREVIEWNET_NETWORK_ADDRESS:      Test Network DNS name, for example 'PREVIEWNET.hedera.com'
#  PREVIEWNET_NETWORK_PORT:         Test Network port number
#  PREVIEWNET_SERVER_NUMBER:        Network Node Address Number receiving Network Requests (assumes Shard = 0, Realm = 0)

name: 'PREVIEWNET Continuous Integration Build & Test'
description: 'Builds the SDK and Executes Integration Tests against the Preview Network'

on:
  push:
    branches: [ previewnet ]

jobs:
  build_and_test:
    environment: PREVIEWNET    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    env:
      BUILD_CONFIGURATION: Release
      DOTNET_NOLOGO: true

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}

    # Commented out for now while we configure
    # the action pipeline in general.  Once we
    # get this working for just builds, we'll 
    # enable tests as well.
    # - name: Integration Tests
    #   run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal
    #   env:
    #     'account:number': ${{ secrets.PREVIEWNET_ACCOUNT_NUMBER }}
    #     'account:publicKey': ${{ secrets.PREVIEWNET_ACCOUNT_PUBLIC_KEY }}
    #     'account:privateKey': ${{ secrets.PREVIEWNET_ACCOUNT_PRIVATE_KEY }}
    #     'mirror:address': ${{ secrets.PREVIEWNET_MIRROR_ADDRESS }}
    #     'mirror:port': ${{ secrets.PREVIEWNET_MIRROR_PORT }}
    #     'network:address': ${{ secrets.PREVIEWNET_NETWORK_ADDRESS }}
    #     'network:port': ${{ secrets.PREVIEWNET_NETWORK_PORT }}
    #     'server:number': ${{ secrets.PREVIEWNET_SERVER_NUMBER }}
