#  Required secrets managed by GitHub.
#
#  TESTNET_ACCOUNT_NUMBER:       The Hedera Test Account Address Number (assumes Shard = 0, Realm = 0)
#  TESTNET_ACCOUNT_PUBLIC_KEY:   Public Key for the root payer account, encoded in Hex
#  TESTNET_ACCOUNT_PRIVATE_KEY:  Private Key for the root payer account, encoded in Hex
#  TESTNET_MIRROR_ADDRESS:       Mirror Node DNS name, for example 'testnet.mirrornode.hedera.com'
#  TESTNET_MIRROR_PORT:          Mirror Node port number
#  TESTNET_NETWORK_ADDRESS:      Test Network DNS name, for example 'testnet.hedera.com'
#  TESTNET_NETWORK_PORT:         Test Network port number
#  TESTNET_SERVER_NUMBER:        Network Node Address Number receiving Network Requests (assumes Shard = 0, Realm = 0)

name: 'TESTNET Continuous Integration Build & Test'

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: [windows-latest, ubuntu-latest, macOS-latest]
    timeout-minutes: 360
    strategy:
      fail-fast: false

    steps:
    - name: 'Build and Test'
      uses: './github/actions/integration-tests'
      with:
        network: TESTNET